---
title: "Exercise 4"
author: "Chris Penfold"
date: "10 December 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Embed a plot

Here's an embedded plot without the accompanying R code (echo=FALSE) where I've changed the size and added a caption

```{r, echo = FALSE, output.width="50%", fig.cap="Fuel consumption by vehicle type"}
library(ggplot2)
ggplot(data = mpg, aes(x = drv, 
                       y = hwy, 
                       colour = drv)) + 
  geom_boxplot()

```


## Embed a table

Here's the code to embed a table which isn't executed (eval=FALSE)

```{r, results="asis", eval=FALSE}
library(arsenal)
table_one <- tableby(drv ~ hwy + class, 
                     data = mpg, 
                     test=TRUE, 
                     total=TRUE)
summary(table_one)
```


## Inline R code

We included `r nrow(mpg)` cars from the mpg dataset in our analyses. The mean fuel consumption of these cars was `r round(mean(mpg$hwy), 3)` mpg (sd = `r round(sd(mpg$hwy), 3)`).